"use client";
import { useCallback, useEffect, useState, type CSSProperties } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { BookOpen, Check, ChevronDown, Circle, LogOut, RefreshCw, ShieldCheck } from "lucide-react";
import { z } from "zod";
import { TraceEvent } from "@/lib/schemas";
import type { AdminFilter, AdminRun, AdminStats } from "@/lib/admin/stats";
import { Button } from "@/components/ui/button";

const Friction = z.object({ stepId: z.string(), title: z.string(), authority: z.string(), medianDays: z.number().nonnegative(), count: z.number().int().nonnegative(), liveReports: z.number().int().nonnegative() });
const Stats = z.object({ syntheticFounders: z.number(), liveFounders: z.number(), founders: z.number(), medianReadyDays: z.number().nullable(), exposureAED: z.number(), unknownPenalties: z.number(), verifiedPercent: z.number().nullable(), completedRuns: z.number(), friction: Friction.array(), authorities: z.string().array(), topStalls: Friction.array(), insights: z.string().array() });
const Runs = z.object({ runs: z.object({ runId: z.string(), ts: z.string(), question: z.string(), agents: z.string().array(), tools: z.number(), verified: z.boolean(), complete: z.boolean(), ms: z.number().nullable(), cached: z.boolean(), events: TraceEvent.array() }).array() });
const locations = ["all", "adgm", "mainland", "hub71", "masdar", "kezad", "twofour54"] as const;
const number = new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 });

export function AdminDashboard({ initial, initialRuns, assumption }: { initial: AdminStats; initialRuns: AdminRun[]; assumption: string }) {
  const router = useRouter();
  const [stats, setStats] = useState(initial);
  const [runs, setRuns] = useState(initialRuns);
  const [filter, setFilter] = useState<AdminFilter>({ family: "all", jurisdiction: "all" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const refresh = useCallback(async (signal?: AbortSignal) => {
    setBusy(true); setError("");
    try {
      const query = new URLSearchParams(filter);
      const responses = await Promise.all([fetch(`/api/admin/stats?${query}`, { signal, cache: "no-store" }), fetch("/api/admin/runs", { signal, cache: "no-store" })]);
      if (responses.some((response) => response.status === 401)) { router.replace("/admin/login"); return; }
      if (responses.some((response) => !response.ok)) throw new Error("unavailable");
      const [next, live] = await Promise.all(responses.map((response) => response.json()));
      setStats(Stats.parse(next)); setRuns(Runs.parse(live).runs);
    } catch { if (!signal?.aborted) setError("The latest data could not be loaded. The previous snapshot is still shown."); } finally { if (!signal?.aborted) setBusy(false); }
  }, [filter, router]);
  useEffect(() => { const controller = new AbortController(); void refresh(controller.signal); const interval = setInterval(() => void refresh(controller.signal), 30000); return () => { controller.abort(); clearInterval(interval); }; }, [refresh]);
  async function logout() { try { const response = await fetch("/api/admin/logout", { method: "POST" }); if (response.ok) { router.replace("/admin/login"); router.refresh(); } } catch { setError("Sign-out could not finish. Please try again."); } }
  const maxStall = Math.max(1, ...stats.friction.map((row) => row.medianDays));

  return <section className="py-10 md:py-14"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.15em] text-primary-ink">Manzil for operators</p><h1 className="mt-3 font-display text-4xl md:text-5xl">Where momentum meets friction.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-ink-muted">A shared view of the founder journey, with simulated patterns and clearly marked live observations.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => void refresh()} disabled={busy}><RefreshCw className={busy ? "motion-safe:animate-spin" : ""} aria-hidden="true" />Refresh</Button><Button variant="ghost" size="icon" onClick={() => void logout()} aria-label="Sign out"><LogOut aria-hidden="true" /></Button></div></div>
    <div className="mt-7 rounded-xl border border-primary/30 bg-primary-soft px-4 py-3 text-sm text-ink"><span className="font-medium">Synthetic demo cohort (240) + live events from this deployment</span><p className="mt-1 text-xs leading-6 text-ink-muted">Live data is process-local and ephemeral; different serverless instances can show different snapshots.</p></div>
    {error && <p role="alert" className="mt-4 text-sm text-coral">{error}</p>}
    <div className="my-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      { label: "Founders", value: number.format(stats.founders), note: `${stats.syntheticFounders} synthetic + ${stats.liveFounders} anonymous live` },
      { label: "Median days to ready", value: stats.medianReadyDays === null ? "—" : number.format(stats.medianReadyDays), note: "Estimate · synthetic profiles, path engine" },
      { label: "AED at stake on watch", value: number.format(stats.exposureAED), note: `Synthetic, next 12 months · excludes ${stats.unknownPenalties} unknown amounts` },
      { label: "Answers verified", value: stats.verifiedPercent === null ? "—" : `${stats.verifiedPercent}%`, note: `${stats.completedRuns} completed live runs · current process` },
    ].map((tile) => <article className="rounded-xl border border-line bg-surface p-5" key={tile.label}><p className="text-xs text-ink-muted">{tile.label}</p><p className="mt-3 break-words font-display text-3xl">{tile.value}</p><p className="mt-3 text-[11px] leading-5 text-ink-muted">{tile.note}</p></article>)}</div>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(250px,1fr)]"><section className="min-w-0 rounded-2xl border border-line bg-surface p-4 sm:p-6" aria-labelledby="radar-heading"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="radar-heading" className="font-display text-2xl">Friction Radar</h2><p className="mt-1 text-xs text-ink-muted">Top 12 steps by median reported duration</p></div><span className="text-[10px] text-ink-muted">Lower <span className="mx-1 inline-block h-2 w-16 rounded-full bg-gradient-to-r from-surface-2 to-coral" aria-hidden="true" /> Higher</span></div>
      <div className="my-5 flex flex-wrap items-center gap-2" aria-label="Friction filters">{(["all", "family", "single"] as const).map((family) => <button key={family} type="button" aria-pressed={filter.family === family} onClick={() => setFilter((current) => ({ ...current, family }))} className={`min-h-11 rounded-full border px-3 text-xs ${filter.family === family ? "border-primary bg-primary-soft text-ink" : "border-line text-ink-muted"}`}>{family === "all" ? "All founders" : family === "family" ? "Family" : "Single"}</button>)}<label className="ml-auto text-xs text-ink-muted"><span className="sr-only">Jurisdiction</span><select aria-label="Jurisdiction" value={filter.jurisdiction} onChange={(event) => setFilter((current) => ({ ...current, jurisdiction: event.target.value as AdminFilter["jurisdiction"] }))} className="h-11 max-w-full rounded-lg border border-line bg-bg px-3 text-ink">{locations.map((location) => <option key={location} value={location}>{location === "all" ? "All jurisdictions" : location.toUpperCase()}</option>)}</select></label></div>
      <div className="overflow-x-auto pb-2" tabIndex={0} aria-label="Friction Radar table, scroll horizontally for all authorities"><div role="table" aria-label="Median duration by step and authority" className="grid min-w-max gap-1" style={{ gridTemplateColumns: `minmax(170px,1.2fr) repeat(${Math.max(1, stats.authorities.length)},minmax(80px,1fr))` }}><div role="columnheader" className="p-2 text-xs text-ink-muted">Step</div>{stats.authorities.map((authority) => <div role="columnheader" className="max-w-24 p-2 text-center text-[10px] leading-4 text-ink-muted" key={authority}>{authority}</div>)}{stats.friction.map((row) => <div role="row" className="contents" key={row.stepId}><div role="rowheader" className="flex max-w-48 items-center gap-2 py-2 pr-3 text-xs leading-5"><span>{row.title}</span>{row.liveReports > 0 && <span className="size-1.5 shrink-0 rounded-full bg-primary" title={`${row.liveReports} live reports`} aria-label={`${row.liveReports} live reports`} />}</div>{stats.authorities.map((authority) => <div role="cell" key={authority} className="flex min-h-10 items-center justify-center rounded-md text-xs font-medium text-ink" title={authority === row.authority ? `${row.medianDays} days median; ${row.count} observations, ${row.liveReports} live. ${assumption}` : "No observations for this step and authority."} style={authority === row.authority ? { background: `color-mix(in srgb,var(--coral) ${Math.round(row.medianDays / maxStall * 65)}%,var(--surface-2))` } as CSSProperties : { background: "var(--bg)" }}>{authority === row.authority ? number.format(row.medianDays) : "—"}</div>)}</div>)}</div></div>
      {!stats.friction.length && <p className="py-8 text-sm text-ink-muted">No observations match these filters.</p>}<details className="mt-4 border-t border-line pt-3 text-xs leading-6 text-ink-muted"><summary className="cursor-pointer">How to read the synthetic sample</summary><p className="mt-2">{assumption}</p><p className="mt-2">Cohort seed: 71. A green dot marks an actual duration report. Values describe observations, not official service promises.</p></details>
    </section><aside className="space-y-4"><section className="rounded-2xl border border-line bg-surface p-5"><h2 className="font-display text-xl">Where founders get stuck</h2><div className="mt-5 space-y-5">{stats.topStalls.map((row) => <div key={row.stepId}><div className="mb-2 flex justify-between gap-3 text-xs"><span>{row.title}</span><strong className="shrink-0 font-medium">{row.medianDays}d</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-surface-2"><div className="h-full rounded-full bg-coral" style={{ width: `${row.medianDays / maxStall * 100}%` }} /></div></div>)}</div></section>{stats.insights.map((insight, index) => <div key={insight} className="rounded-xl border border-line bg-primary-soft p-4"><p className="mb-2 text-[10px] uppercase tracking-wider text-primary-ink">Observed pattern {index + 1} · deterministic</p><p className="text-xs leading-6 text-ink">{insight}</p></div>)}</aside></div>
    <section className="mt-7 overflow-hidden rounded-2xl border border-line bg-surface" aria-labelledby="runs-heading"><div className="flex items-center justify-between gap-3 p-5 sm:p-6"><div><h2 id="runs-heading" className="font-display text-2xl">Live agent runs</h2><p className="mt-1 text-xs text-ink-muted">Latest 20 in this process · expand to inspect the trace</p></div><ShieldCheck aria-hidden="true" className="size-5 text-primary" /></div>{runs.length ? runs.map((run) => <details className="group border-t border-line" key={run.runId}><summary className="flex cursor-pointer list-none flex-wrap items-center gap-3 px-5 py-4 text-xs"><span className={`size-1.5 rounded-full ${run.cached ? "bg-amber" : "bg-primary"}`} aria-label={run.cached ? "cached" : "live"} /><span className="min-w-0 flex-1"><span className="block break-words text-ink">{run.question}</span><span className="mt-1 block text-[10px] text-ink-muted">{new Date(run.ts).toLocaleString("en-GB", { timeZone: "Asia/Dubai" })} · {run.agents.join(" → ") || "Run starting"}</span></span><span className="text-ink-muted">{run.tools} tools</span><span className="text-ink-muted">{run.ms === null ? "Running" : `${run.ms} ms`}</span><span className="inline-flex items-center gap-1">{run.verified ? <Check className="size-3 text-primary" /> : <Circle className="size-3 text-ink-muted" />}{run.verified ? "Verified" : run.complete ? "Not verified" : "Pending"}</span><ChevronDown aria-hidden="true" className="size-4 transition-transform group-open:rotate-180" /></summary><ol aria-label="Run trace" className="space-y-3 border-t border-line bg-bg px-6 py-5">{run.events.filter((event) => event.kind !== "message_delta").map((event, index) => <li key={`${event.spanId}-${index}`} className="flex flex-wrap items-center gap-2 text-xs leading-6"><span className="rounded-md border border-line px-2 text-primary-ink">{event.kind.replaceAll("_", " ")}</span><span>{event.agent}</span>{event.name && <span className="text-ink-muted">{event.name}</span>}{event.ms !== undefined && <span className="ml-auto font-mono text-ink-muted">{event.ms} ms</span>}</li>)}</ol></details>) : <p className="border-t border-line px-6 py-8 text-sm text-ink-muted">No live runs are recorded in this process yet. Completed Ask Manzil requests appear here while this instance remains warm.</p>}</section>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 text-xs text-ink-muted"><p>Regulatory amounts come from the sourced rules. Synthetic reporting is labelled throughout.</p><Link href="/rulebook" className="inline-flex min-h-11 items-center gap-2 text-primary-ink hover:underline"><BookOpen aria-hidden="true" className="size-4" />Manzil Rulebook</Link></div>
  </section>;
}
